.\" vim: set ft=nroff
.\" # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
.\" #
.\" #              C E D A R
.\" #          S O L U T I O N S       "Software done right."
.\" #           S O F T W A R E
.\" #
.\" # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
.\" #
.\" # Author   : Kenneth J. Pronovici <pronovic@ieee.org>
.\" # Language : nroff
.\" # Project  : Christmas
.\" # Package  : Fun scripts and programs
.\" # Revision : $Id: secret-santa.conf.5 921 2005-12-07 19:30:04Z pronovic $
.\" # Purpose  : Manpage for secret-santa configuration.
.\" #
.\" # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
.\"
.\" This file was created with a width of 132 characters, and NO tabs.
.\"
.TH secret-santa.conf "5" "December 2005" "Secret Santa" "Kenneth J. Pronovici"
.SH NAME
secret-santa.conf \- The configuration file for the secret-santa script
.SH SYNOPSIS
.PP
The configuration file provided to secret-santa does not have to be
named \fIsecret-santa.conf\fR, but must match the format described
below.  The secret-santa configuration file is written in XML, and an
example file can be found with the secret-santa source code.  This
manpage documents the file format and parameters for reference purposes.
See the manpage for secret-santa(1) for more information on the
secret-santa script itself.
.PP
.SH "GENERAL FORMAT"
.PP
The main configuration section, <secret-santa>, contains two other sections:
.NF

 <exchange>    General exchange configuration
 <group>       Information describing the exchange group

.PP
.SH "EXCHANGE SECTION"
.PP
The <exchange> section contains exactly six elements:
.NF

 <name>        The name of the exchange
 <organizer>   Details about the organizer
 <date-time>   The date/time of the exchange
 <theme>       The theme of the exchange
 <cost>        The suggested cost of a gift
 <greeting>    Free-form comments for the email

.PP
All fields except <organizer> are free-form text.  The
<organizer> field contains three other fields:
.NF

 <name>        The name of the organizer
 <email>       Organizer's email address
 <phone>       Organizer's phone number

.PP
This is an example <exchange> section:
.NF

 <exchange>
  <name>Sample Exchange</name>
  <organizer>
   <name>Sample Organizer</name>
   <email>test@dummy.org</email>
   <phone>612.555.1212</phone>
  </organizer>
  <date-time>Christmas Day, 2002 (time TBD)</date-time>
  <theme>Free Software</theme>
  <cost>$0-$0</cost>
  <greeting>
Hello!  This exchange is a test exchange, that shouldn't
really be used for anything.  You would put the real greeting
that you'd like at the top of the email into this field.
  </greeting>
 </exchange>

.PP
.SH "GROUP SECTION"
.PP
The <group> section contains one or more <person> sections.
Each person section contains the following fields:
.NF

 <id>          A unique identifer for this person
 <name>        Full name 
 <nickname>    Nickname
 <email>       Email address
 <conflicts>   Any conflicts, identified by id

.PP
The <id> just has to be unique.  You can use numbers (simple)
or if there are no duplicates, first name or last name, etc.
There is no check to ensure that ids are actually unique, so
be careful!
.PP
The <conflicts> field contains a list of IDs that this person
should not have assigned as their buddy.  If there are no conflicts,
just list an empty tag, i.e. <conflicts/>.
.PP
Here is an example person with no conflicts:
.NF

 <person>
  <id>3</id>
  <name>Person Three</name>
  <nickname>Three</nickname>
  <email>three@dummy.org</email>
  <conflicts/>
 </person>

.PP
Here is an example person with two conflicts:
.NF

 <person>
  <id>4</id>
  <name>Person Four</name>
  <nickname>Four</nickname>
  <email>four@dummy.org</email>
  <conflicts>
   <id>1</id>
   <id>2</id>
  </conflicts>
 </person>

.PP
Be careful when assigning conflicts!  You need to leave some
possibilities open, and if you assign too many conflicts, there
may just not be any way to generate a valid exchange and still
satisfy those conflicts.
.PP
.SH AUTHOR
Written by Kenneth J. Pronovici
.SH COPYRIGHT
Copyright (c) 2002,2005 Kenneth J. Pronovici.
.br
This is free software; see the source for copying conditions.  There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
.SH "SEE ALSO"
secret-santa(1)
