.\" vim: set ft=nroff .\"
.\" # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
.\" #
.\" #              C E D A R
.\" #          S O L U T I O N S       "Software done right."
.\" #           S O F T W A R E
.\" #
.\" # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
.\" #
.\" # Author   : Kenneth J. Pronovici <pronovic@ieee.org>
.\" # Language : nroff
.\" # Project  : Christmas
.\" # Package  : Fun scripts and programs
.\" # Revision : $Id: secret-santa.1 921 2005-12-07 19:30:04Z pronovic $
.\" # Purpose  : Manpage for secret-santa script.
.\" #
.\" # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
.\"
.\" This file was created with a width of 132 characters, and NO tabs.
.\"
.TH secret-santa "1" "December 2005" "Secret Santa" "Kenneth J. Pronovici"
.SH NAME
secret-santa \- Provide Secret Santa assignments for a group of people
.SH SYNOPSIS
.B secret-santa
[\fIoptions\fR] config-file
.SH DESCRIPTION
.PP
A "Secret Santa" exchange is one where a group of a people get together
and each exchange gifts with one other person from that group.  The
exchange assignments are supposed to be secret, so that no one knows
ahead of time who they will get their gift from.  Usually, there's a
small ($5, $10, $15) limit on the size of the gift.  Another name for
this type of exchange is a "grab bag" exchange.
.PP
Every Secret Santa exchange has several elements:
.NF

   A group of people
   A "theme" for the exchange
   A maximum cost for each gift
   A date/time that the exchange will take place
.PP
We sometimes place limits on the way the exchange is generated.  For
instance, a person should not be assigned themselves as a partner, and
we may sometimes not want to group two other particular people together
(say, husband and wife at a big party).
.PP
This script will generate an exchange and then notify the group
partipants of their assignment via email.
.SH CONFIGURATION
.PP
See the manpage for secret-santa.conf(5) for information on the
configuration file format.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Display usage/help listing.
.TP
\fB\-V\fR, \fB\-\-version\fR
Display version information.
.TP
\fB\-a\fR, \fB\-\-attempts\fR
Number of attempts to take.  For some configurations, it may be
difficult to find a valid exchange in a single attempt.  By default, up
to 10 attempts will be made.
.TP
\fB\-r\fR, \fB\-\-results\fR
Dump results to standard output.  This option is useful for testing
along with the --noemail option, or in order to keep a list of
assignments, in case a participant were to lose his or her email.
.TP
\fB\-o\fR, \fB\-\-orgonly\fR
Generate email to organizer only.  This option is useful for testing, in
order to see what emails to participants will look like.
.TP
\fB\-n\fR, \fB\-\-noemail\fR
Do not send any emails.
.TP
\fB\-c\fR, \fB\-\-autoconflict\fR
Create automatic conflicts between gift-givers, so two people are never
assigned to give each other gifts.  This option might make it difficult
to find a solution, especially for small groups of participants or if
other conflicts are assigned in configuration.
.SH NOTES
.PP
It's possible that for a given pass, we might not be able to build a
valid exchange.  This might happen, for instance, if we get to the point
where the only people left to be assigned all conflict with the person 
we're trying to make an assignment for.
.PP
Since we're generating assigments pseudo-randomly, this isn't a
permanent failure.  We'll just try again (up to 10 times) to see if we
can make it work.  If it still doesn't work, there are you potential
fixes: either modify configuration (to change conflicts) or increase the
number of attempts (which might make a difference for larger groups).
.SH BUGS
.PP
There probably are bugs in this code.  I whipped it together pretty
quickly.  However, it seems to work fine.  If you find a bug, please
report it.  If possible, give me all error messages that the script
printed, and provide the output that the script gives when run with 
the --orgonly and --report options enabled.
.PP
I would eventually like to add support for reply-to addresses and
few other things, but given how often I use the script, I don't think
I'll get around to it.  Patches accepted. 
.PP
Report bugs to <support@cedar-solutions.com>.
.SH AUTHOR
Written by Kenneth J. Pronovici
.SH COPYRIGHT
Copyright (c) 2002,2005 Kenneth J. Pronovici.
.br
This is free software; see the source for copying conditions.  There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
.SH "SEE ALSO"
secret-santa.conf(5)
